//POST http://127.0.0.1:8080/v1/admin/login HTTP/1.1
//{
//    "account":"12010110001",
//    "password":"password"
//}

POST http://127.0.0.1:8080/v1/exam/addone HTTP/1.1

{    
	"name":"生物化学",         
	"start-time":"9：00",    
	"duration":"100",     
	"date":"09-11",         
	"position":"理论楼201",     
	"number":"123",      
	"grade":"2020",       
	"specialty":"临床医学",    
	"class":["临床试验1班","口腔1班"],        
	"organizer":"生物化学教研室",    
	"content":[
        {"title":"各种蛋白质平均含氮量约为","choice": ["0.6%", "6%", "16%", "26%", "36%"]}
    ]
}