POST http://127.0.0.1:8080/v1/admin/login HTTP/1.1
{
    "account":"12010110001",
    "password":"password"
}
###
POST http://127.0.0.1:8080/v1/exam/addone HTTP/1.1

{    
 	"name":"中国近代史",         
 	"start-time":"9：00",    
 	"duration":"100",     
 	"day":"19",
    "month":"3",         
 	"position":"理论楼201",     
 	"number":"123",      
 	"grade":"2020",       
 	"specialty":"临床医学",    
 	"class":["临床试验1班","口腔1班"],        
 	"organizer":"生物化学教研室",    
 	"content":[
         {"title":"各种蛋白质平均含氮量约为","choice": ["0.6%", "6%", "16%", "26%", "36%"]}
    ]
}
###
Get http://127.0.0.1:8080/v1/exam/recent HTTP/1.1
###
Get http://127.0.0.1:8080/v1/exam/list HTTP/1.1
###
Post http://127.0.0.1:8080/v1/exam/content HTTP/1.1

{
	"id":"AbzvMhS46KCNTeLl6UV2XR0szKxaUjIm"
}
###
Post http://127.0.0.1:8080/v1/exam/delone HTTP/1.1

{
	"id":"AbzvMhS46KCNTeLl6UV2XR0szKxaUjIm"
}


